export enum ActionEnum {
  // Individual
  SYNC_NOTIFICATIONS = 'SYNC_NOTIFICATIONS',
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION',
  UPDATE_NOTIFICATION_STATUS = 'UPDATE_NOTIFICATION_STATUS',
  // Group
  SYNC_NOTIFICATION_GROUPS = 'SYNC_NOTIFICATION_GROUPS',
  ADD_NOTIFICATION_GROUP = 'ADD_NOTIFICATION_GROUP',
  UPDATE_NOTIFICATION_GROUP = 'UPDATE_NOTIFICATION_GROUP',
  REMOVE_NOTIFICATION_GROUP = 'REMOVE_NOTIFICATION_GROUP'
};