export enum ActionEnum {
  SYNC_USER_DATA = 'SYNC_USER_DATA',
  SWITCH_USER_THEME = 'SWITCH_USER_THEME',
  CLEAR_USER_DATA_AFTER_LOGOUT = 'CLEAR_USER_DATA_AFTER_LOGOUT',
  UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS'
}